version: '2.1'

services:

#  caddy:
#    image: truedevops/caddy_caddy
#    container_name: caddy
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    links:
#      - "nexus"
#    environment:
#      - CADDYPATH=/etc/caddycerts
#      - ACME_AGREE=true
#    volumes:
#      - ${PWD}/Caddyfile:/etc/Caddyfile
#      - ${PWD}/caddy:/etc/caddycerts

  nexus:
    image: sonatype/nexus3
#    image: hub.vadim.pp.ua/nexus3:1.0.0
    container_name: nexus
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ../../docker_volume/nexus-data/:/nexus-data


  jenkins:
    image: jenkins/jenkins:2.302
#    image: hub.vadim.pp.ua/nexus3:1.0.0
    container_name: jenkins
    restart: always
    ports:
      - 8083:80
      - 50000:50000
    volumes:
      - ../../docker_volume/jenkins/:/var/jenkins_home

