version: '2.1'

services:


  nexus:
    image: sonatype/nexus3
#    image: hub.vadim.pp.ua/nexus3:1.0.0
    container_name: nexus
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ../../docker_volume/nexus-data:/nexus-data
