# my global config
global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.
  evaluation_interval: 5s # By default, scrape targets every 5 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #     monitor: 'Ignited'

#basic_auth_users:
#  admin: $2b$12$hNf2lSsxfm0.i4a.1kVpSOVyBCfIB51VRjgBUyv6kdnyTlgWj81Ay

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - '*.rules'
  # - 'alert.rules'
  # - 'blackbox.rules'
  # - 'cadvisor.rules'
  # - 'mysql.rules'
  # - 'backup.rules'
  # - 'cron.rules'
  # - 'container.rules'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
  - job_name: 'node'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
         - targets:
           - localhost:9090
           - node-exporter:9100
           - home.vadim.pp.ua:9100
           - n6.gettorrent.cloud:9100
  - job_name: 'cadvisor-infra'
    scrape_interval: 5s
    scheme: http
    static_configs:
         - targets:
           - cadvisor:8080
  - job_name: 'postgresql-exporter'
    static_configs:
         - targets: 
           - my.gettorrent.cloud:9187
  - job_name: 'cadvisor-home'
    scrape_interval: 5s
    scheme: http
    static_configs:
         - targets:
           - home.vadim.pp.ua:9595
  - job_name: 'cadvisor-n6'
    scrape_interval: 5s
    scheme: http
    static_configs:
         - targets:
           - n6.gettorrent.cloud:9595
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://gettorrent.cloud
        - https://my.gettorrent.cloud
        - http://aquaflora.com.ua
        - https://megahost.com.ua
        - https://megahost.com.ua/billing
        - https://n2.gettorrent.cloud
        - https://n6.gettorrent.cloud
        - https://n7.gettorrent.cloud
        - https://n8.gettorrent.cloud
        - https://n9.gettorrent.cloud
        - https://n10.gettorrent.cloud
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"  # Blackbox exporter.
#      - target_label: region
#        replacement: "local"
  # - job_name: 'ec2'
  #   ec2_sd_configs:
  #     - region: eu-central-1
  #       access_key: 
  #       secret_key: 
  #       port: 9100
  #   relabel_configs:
  #     #- source_labels: [__meta_ec2_instance_id]
  #     #  target_label: instance_id
  #     #- source_labels: [__meta_ec2_instance_type]
  #     #  target_label: instance_type
  #     #- source_labels: [__meta_ec2_private_dns_name]
  #     #  target_label: private_dns_name
  #     - source_labels: [__meta_ec2_private_ip]
  #       target_label: private_ip
  #     #- source_labels: [__meta_ec2_public_dns_name]
  #     #  target_label: public_dns_name
  #     - source_labels: [__meta_ec2_public_ip]
  #       target_label: public_ip
  #     - source_labels: [__meta_ec2_tag_Name]
  #       target_label: tag_Name
  #     - source_labels: [__meta_ec2_tag_ansible_name]
  #       target_label: ansible_name
  # - job_name: 'DigitalOcean'
  #   scrape_interval: 5s
  #   static_configs:
  #        - targets:
  #          - me1-do.igenv.com:9100
  # - job_name: mysql
  #   static_configs:
  #     - targets:
  #       - mm-1-stage.igenv.priv:9104
  #       - mm-1-prod.igenv.priv:9104
  #       - ms-1-prod.igenv.priv:9104
  #       - mm-1-prod.alterme.app:9104
  #       - mm-1-prod-cms.igenv.com:9104
  #       - ms-1-prod-cms.igenv.com:9104
  # - job_name: redis
  #   static_configs:
  #     - targets:
  #       - 172.31.10.96:9121
  #       - 172.31.44.16:9121
  # - job_name: rabbitmq
  #   static_configs:
  #     - targets:
  #       - rabbitmq-prod-1.igenv.priv:15692
  #       - rabbitmq-prod-2.igenv.priv:15692
  #       - rabbitmq-prod-3.igenv.priv:15692
  #       - rabbitmq-stage.igenv.priv:15692
  - job_name: statsd-stage
    static_configs:
      - targets:
        - statsd-exporter-stage:9102
  # - job_name: 'aws-billing'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: 
  #       - aws-exporter:5000
  # - job_name: 's3_backup'
  #   metrics_path: /probe
  #   static_configs:
  #     - targets:
  #       - bucket=backup-hotstories.me;prefix=mysql;
  #       - bucket=backup-hotstories.me;prefix=data;
  #       - bucket=backup-testrail.igenv.com;prefix=mysql;
  #       - bucket=backup-testrail.igenv.com;prefix=data;
  #       - bucket=backup-mysql-igenv.com;prefix=prod;
  #       - bucket=backup-mysql-igenv.com;prefix=stage;
  #       - bucket=backup-gitlab.igenv.com;
    # relabel_configs:
    #   - source_labels: [__address__]
    #     regex: '^bucket=(.*);prefix=(.*);$'
    #     replacement: '${1}'
    #     target_label: '__param_bucket'
    #   - source_labels: [__address__]
    #     regex: '^bucket=(.*);prefix=(.*);$'
    #     replacement: '${2}'
    #     target_label: '__param_prefix'
    #   - target_label: __address__
    #     replacement: s3-exporter:9340  # S3 exporter.
