#!/bin/bash

tar -zcf  /tmp/docker_volume_$(date +%Y%m%d_%H%M).tar.gz -P /home/vadim/docker_volume

mv /tmp/docker_volume_*.tar.gz  /yandexdisk/elk-server/

find /yandexdisk/elk-server/docker_volume -atime +4 | xargs rm -f
