#!/usr/bin/expect
spawn mount.davfs https://webdav.yandex.ru /yandexdisk
expect "Username:"
send "magellane89@yandex.ru\r"
expect "Password:"
send "subaru\r"
expect eof
#apt install davfs2 expect
#chmod +x /usr/local/bin/yandexdisk
#mkdir -p /yandexdisk
