# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
        config.vm.define "master" do |master|
        master.vm.hostname = "debian-8.11"
#        master.vm.box = "zavadi/test-debian"
        master.vm.box = "bento/debian-8.11"
#        master.vm.box_url = "file:///D:/backup/gettor-debian-vm.box"
        config.vm.box_check_update = false
        config.vm.define "debian-8.11"
        config.vm.network  "forwarded_port", guest: 8080, host: 8080, auto_correct: true
#        config.vm.network "private_network", ip: "192.168.40.15"
#        master.vm.network "public_network", ip: "192.168.7.210", netmask: "255.255.255.0", :bridge => 'Realtek USB GbE Family Controller'
        config.ssh.username = "vagrant"
        config.ssh.password = "vagrant"
		config.vm.provision "shell", path: "script.sh"
        config.vm.provider :virtualbox do |v1|
        v1.memory = 4096
        v1.customize ["modifyvm", :id, "--cpuexecutioncap", "95"]
        v1.cpus = 6
#       v1.customize ["modifyvm", :id, "--vrde", "off"]
#        v1.customize ["modifyvm", :id, "--vrdeport", "16914"]
#       v1.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]

    end
end



end

