{
 "title": "Prometheus Blackbox Exporter",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Probe Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "target" },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 15 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 15 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 32 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 32 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 32 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 49 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 49 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 49 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 64 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 66 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 66 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 66 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 77 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 79 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 81 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 83 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 83 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 83 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 83 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 94 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 96 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 98 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 100 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 100 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 100 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 100 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 111 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 111 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 111 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 113 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 115 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 117 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 117 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 117 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 117 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 128 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 128 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 128 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 130 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 132 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 134 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 134 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 134 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 134 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 145 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 145 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 145 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 147 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 149 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 151 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 151 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 151 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 151 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 162 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 162 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 162 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 164 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 166 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 168 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 168 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 168 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 168 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 179 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 179 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 179 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 181 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 183 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 185 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 185 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 185 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 185 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Site up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"https://my.gettorrent.cloud\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"https://my.gettorrent.cloud\"} - time()"
    }
   ]
  }
 ]
}