version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
   # image: prom/prometheus:v2.19.2
    image: prom/prometheus:v2.22.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    restart: always
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:7.3.2
#    image: grafana/grafana:7.2.0
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
#      - ./grafana/ldap.toml:/etc/grafana/ldap.toml
#      - ./grafana/admin_password:/admin_password
    env_file:
      - config.monitoring

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.18.0
    ports:
      - 9115:9115
    volumes:
      - ./blackboxexporter/:/etc/blackboxexporter/
    command:
      - '--config.file=/etc/blackboxexporter/config.yml'
    restart: always
  
  statsd-exporter-stage:
    image: prom/statsd-exporter:v0.18.0
    ports: 
      - 9102:9102
      - 9125:9125/udp
    volumes:
      - ./statsd-exporter-stage/statsd_mapping.yml:/tmp/statsd_mapping.yml
    command:
      - '--statsd.mapping-config=/tmp/statsd_mapping.yml'
#      - '--statsd.listen-udp="0.0.0.0:9125"'
#      - '--web.telemetry-path="/metrics"'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    # ports:
    # - 9595:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    deploy:
      mode: global