cluster.name: "docker-cluster"
network.host: 0.0.0.0
cluster.max_shards_per_node: 45
#index.number_of_shards: 1
#index.number_of_replicas: 0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true

